# Use an official nodejs runtime as a parent image
FROM node:10

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in packages.json
RUN npm install && npm rebuild node-sass

# Make port 80 available to the world outside this container
EXPOSE 4200

# Define environment variable
# ENV NAME World

# Run angular server when the container launches
CMD ["npm", "run", "start"]